services:
  ledashboard:
    image: florianval/ledashboard:latest
    network_mode: host
    volumes:
      - ./data:/app/data
      - ./sources.yaml:/app/sources.yaml
    environment:
      - HOST=0.0.0.0
      - PORT=3002
      - DATABASE_PATH=/app/data/ledashboard-v2.sqlite
      - SOURCES_PATH=/app/sources.yaml
    restart: unless-stopped
