[agent]
  interval = "60s"
  flush_interval = "60s"
  omit_hostname = true

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  report_active = true

[[inputs.mem]]

[[inputs.disk]]
  mount_points = ["/"]

[[inputs.net]]
  interfaces = ["en0"]

[[inputs.system]]

[[outputs.prometheus_client]]
  listen = "0.0.0.0:9273"
  basic_username = "${TELEGRAF_PROM_USERNAME}"
  basic_password = "${TELEGRAF_PROM_PASSWORD}"
